In [22]:
import numpy as np
import copy

In [215]:
class blotto_solver():
    
    def __init__(self, num_battlegrounds, num_soldiers):
        self.num_battlegrounds = num_battlegrounds
        self.num_soldiers = num_soldiers
        self.strategies = []
        self.payoff_rule = None
        self.payoff_matrix = None

    def set_payoff_rule(self, payoff_rule):
        self.payoff_rule = payoff_rule
    
    def __generate_strategies(self, cur_battleground=0, used_soldiers=0, cur_strategy=None):
        if cur_strategy is None:
            cur_strategy = np.zeros(self.num_battlegrounds)

        if cur_battleground == self.num_battlegrounds:
            self.strategies.append(cur_strategy)
            return 0 #TODO: return smth
        
        for i in range(0, self.num_soldiers - used_soldiers + 1):
            print(cur_battleground, i)
            cur_strategy[cur_battleground] = i
            self.__generate_strategies(cur_battleground + 1, used_soldiers + i, copy.deepcopy(cur_strategy))

    def generate_strategies(self):
        self.__generate_strategies()
        self.strategies = np.array(self.strategies, dtype=np.int16)

    def generate_payoff_matrix(self):
        self.payoff_matrix = self.payoff_rule(self.strategies, self.strategies)

        


In [281]:
a = blotto_solver(2, 2)
a.generate_strategies()
xd1 = a.strategies
xd1

0 0
1 0
1 1
1 2
0 1
1 0
1 1
0 2
1 0


array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0]], dtype=int16)

In [280]:
def test(a, b, points_to_win):
    result = np.cumsum(np.sign(a - b) * (np.arange(a.shape[2]) + 1), axis=2)
    idx = np.argmax(abs(result) >= points_to_win, axis=2)

    #no point in broadcasting here, just loop
    for i in range(a.shape[0]):
        for j in range(b.shape[0]):
            if idx[i,j] == 0:
                result[i,j] = 0
            else:
                result[i,j] = np.sign(result[i,j,idx[i,j]])

    result = np.max(result, axis=2)

    return result

In [279]:
test(xd1[:,None], xd1, 2)

[[ 0 -1 -1  0 -1  0]
 [ 1  0 -1  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  0  0  0 -1  0]
 [ 1  0  0  1  0  0]
 [ 0  0  0  0  0  0]]
